name: Docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '18.x'
      - name: Bootstrap
        run: |
          npm ci
          npx lerna bootstrap
          npx lerna run build
      - name: Install mkdocs deps/plugins
        run: |
          pip install mkdocs-material
          pip install mkdocs-include-markdown-plugin
      - name: Create the docs directory locally in CI
        run: npm run export-typedocs
      - name: Deploy 🚀
        run: mkdocs gh-deploy --force
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'docs'
          destination-github-username: 'codeweb05'
          destination-repository-name: 'repo2'
          target-directory: 'docs/arc-api-docs'
          user-email: 'github-actions@github.com'
          user-name: ${{ github.actor }}
          target-branch: main
          commit-message: ${{ github.event.head_commit.message }}
      - name: Pushes Readme file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'README.md'
          destination_repo: 'codeweb05/repo2'
          destination_folder: 'docs/arc-api-docs'
          rename: 'index.md'
          user_email: 'github-actions@github.com'
          user_name: ${{ github.actor }}
          commit_message: ${{ github.event.head_commit.message }}
