name: Transfer File
on:
  push:
    branches:
      - main
jobs:
  transfer-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
        with:
          source_file: 'README.md'
          destination_repo: 'codeweb05/repo2'
          destination_folder: '.'
          user_email: 'sj40863@email.com'
          user_name: 'saurabh'
          commit_message: 'A custom message for the commit'

