name: Transfer File
on:
  push:
    branches:
      - main
jobs:
  transfer-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'README.md'
          rename: 'index1.md'
          destination_repo: 'codeweb05/repo3'
          user_email: 'sj40863@email.com'
          user_name: 'saurabh1'
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'test'
          destination-github-username: 'codeweb05'
          destination-repository-name: 'repo3'
          target-directory: 'test1'
          user-email: carles3@pina.cat
          target-branch: main


