name: Transfer File
on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
jobs:
  transfer-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
        with:
          source_file: 'README.md'
          destination_repo: 'codeweb05/repo2'
          rename: 'index1.md'
          user_email: 'sj40863@email.com'
          user_name: 'saurabh1'


