name: Transfer File
on:
  push:
    branches:
      - main
jobs:
  transfer-file:
    runs-on: ubuntu-latest
    steps:
      - name: Push generated webpage to another repository
        uses: nkoppel/push-files-to-another-repository@v1.1.1
        env:
          API_TOKEN_GITHUB: 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
        with:
          source-files: "README.md"
          destination-username: "codeweb05"
          destination-repository: "repo2"
          destination-directory: "projects"
          commit-email: "sj40863@gmail.com"
          destination-branch: "main"

