name: Transfer File
on:
  push:
    branches:
      - main
jobs:
  transfer-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'README.md'
          rename: 'index1.md'
          destination_repo: 'codeweb05/repo3'
          user_email: 'sj40863@email.com'
          user_name: 'saurabh1'
      - name: Pushes test folder
        uses: datalbry/copy_folder_to_another_repo_action@1.0.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: 'test'
          destination_repo: 'codeweb05/repo3'
          destination_folder: 'test-dir'
          user_email: 'sj40863@gmail.com'
          user_name: 'codeweb05'
          commit_msg: ${{ github.event.head_commit.message }}


