name: Transfer File
on:
  push:
    branches:
      - main
jobs:
  transfer-file:
    runs-on: ubuntu-latest
    steps:
      - name: Push generated webpage to another repository
        uses: nkoppel/push-files-to-another-repository@v1.1.1
        env:
          API_TOKEN_GITHUB: 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
        with:
          source-files: "README.md"
          destination-username: "codeweb05"
          destination-repository: "repo2"
          destination-directory: "projects"
          commit-email: "sj40863@gmail.com"

